bundler_args: --without yard guard metrics benchmarks
before_install:
  - gem install bundler --pre
branches:
  only:
    - release-1.2
before_script:
  - mysql -e "create database datamapper_alternate_tests;"
  - mysql -e "create database datamapper_default_tests;"
  - psql  -c "create database datamapper_default_tests;" -U postgres
  - psql  -c "create database datamapper_alternate_tests;" -U postgres
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ree
en:
  # specs need to be adapted for this to pass
  #
  #- "GIT_BRANCH=release-1.2 ADAPTER=in_memory"
  - "GIT_BRANCH=release-1.2 ADAPTER=yaml"
  - "GIT_BRANCH=release-1.2 ADAPTER=sqlite"
  - "GIT_BRANCH=release-1.2 ADAPTER=mysql DM_DB_USER=root DM_DB_PASSWORD=''"
  - "GIT_BRANCH=release-1.2 ADAPTER=postgres DM_DB_USER=postgres DM_DB_PASSWORD=''"
matrix:
  allow_failures:
    - ree
notifications:
  irc: "irc.freenode.org#datamapper"
